---
# tasks file for common

# https://github.com/ansible/ansible-modules-core/issues/2951
- name: Hack to resolve problem with Ansible apt update - manually purge apt cache
  sudo: true
  shell: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'
