---
# tasks file for common

# https://github.com/ansible/ansible-modules-core/issues/2951
- name: Hack to resolve problem with Ansible apt update - manually purge apt cache
  become: true
  shell: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'

# sudo apt-get update
#- name: Update APT cache
#  apt: update_cache=yes cache_valid_time=3600