- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install base development/server packages
  apt: pkg={{item}} state=present
  with_items:
    - deluge
    - deluge-gtk
    - deluge-web
    - deluged
    - deluge-console
