---
# Install Docker and Docker Compose

- name: Check if docker-engine is installed
  command: dpkg-query -W docker-engine
  register: docker_installed
  failed_when: docker_installed.rc > 1
  changed_when: docker_installed.rc == 1

- name: Install Docker if missing
  shell: wget -qO- https://get.docker.com/ | sh
  when: docker_installed.rc != 0

- name: Update existing Docker installation if required
  apt: name=docker-engine update_cache=yes only_upgrade=yes
  become: yes

- name: Install / update Docker Compose
  pip: name={{item}} state=latest
  with_items:
    - pip
    - docker-compose
  become: true

- name: Install Docker Compose (without pip)
  get_url: url=https://github.com/docker/compose/releases/download/1.10.0/docker-compose-Linux-x86_64
           dest=/usr/local/bin/docker-compose
           owner=root
           group=root
           mode=u+x

# sudo usermod -aG docker $USER
- name: Add primary user to the 'docker' group
  user: name={{main_user}} groups=docker append=yes
