- name: Add Dropbox repo key
  apt_key: keyserver=pgp.mit.edu id=5044912E

- name: Add another Dropbox repo key
  apt_key: id='FC918B335044912E' keyserver='keyserver.ubuntu.com'

- name: Add Dropbox repo
  apt_repository:
    repo='deb http://linux.dropbox.com/ubuntu {{ubuntu_release_lts}} main'
    filename='dropbox'
    state=present

- name: Install Dropbox
  apt: pkg={{item}} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - python-gpgme
    - dropbox

- name: Increase fs.inotify.max_user_watches for Dropbox
  sysctl:
    name=fs.inotify.max_user_watches
    value=100000
    state=present
