---
- name: Install an up to date Erlang package repo
  apt: deb="https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
       update_cache=yes
  become: yes

- name: Install Erlang and Elixir
  apt: pkg={{item}} state=present
  with_items:
    - esl-erlang
    - elixir
