---
- name: Install an up to date Erlang package repo
  apt: deb="https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
  become: yes

# - include: delete-apt-cache-hack.yml

- name: Install Erlang and Elixir
  apt: pkg={{item}} update_cache=yes state=present
  with_items:
    - esl-erlang
    - elixir
