---
- name: Add Java PPA (ppa:webupd8team/java)
#  apt_repository: repo='ppa:webupd8team/java'
  command: apt-add-repository -y ppa:webupd8team/java

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Accept Oracle Java license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
#  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Oracle Java 8
  apt: pkg={{item}} state=present
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default