---
# tasks file for desktop

- include_tasks: find-ubuntu-flavor.yml
  tags: [always]

- include_tasks: repositories.yml

#####

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Safe apt-get upgrade
  apt: upgrade=safe

- name: Install base development/server packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - mosh
    - openssh-server
    - samba
    - samba-common
    - smbclient
    - samba-vfs-modules
    - build-essential
    - git
    - ubuntu-make
    - vim
    - htop
    - byobu
    - ipython
    - at
    - aria2
    - microcode.ctl
    - intel-microcode
    - ppa-purge
    - curl
    - ncftp
    - nmap
    - gedit
    - xrdp
    - runc
    - speedtest-cli
    - golang-go

- include_tasks: python.yml
  tags: [dev, python]

- include_tasks: tor.yml
  tags: [privacy, tor]

- name: Install desktop packages
  apt: pkg={{item}} state=present
  with_items:
    - vlc
    - gimp
    - blender
    - vim-gnome
    - gparted
    - nautilus-actions
    - gksu
    - ubuntu-restricted-extras
    - humanity-icon-theme

- name: Remove packages I don't use
  apt: pkg={{item}} state=absent purge=yes
  with_items:
    - evolution
    - rhythmbox
    - empathy
    - gnome-photos
    - gnome-contacts
    - gnome-calendar
    - gnome-mines
    - gnome-sudoku
    - aisleriot
    - totem
    - deja-dup
    - thunderbird

- include_tasks: gnome3.yml
  tags: ['gnome3']

- include_tasks: singularity-apt.yml
  tags: ['singularity']

#- name: Install Steam
#  apt: pkg={{item}} state=present
#  with_items:
#    - steam

# TODO: Need to deal with some interactive dpkg-configure options here
#       before we can automatically install this.
#- name: Install localepurge
#  apt: pkg={{item}} state=present
#  with_items:
#    - localepurge

- name: Install the 'grin' tool
  tags: [dev]
  pip: name=grin state=latest
  become: true

- name: Accept Oracle Java license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
#  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Oracle Java 8
  apt: pkg={{item}} state=present
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default

- name: Install Ubuntu Make from PPA
  tags: [dev]
  apt: pkg={{item}} state=present
  with_items:
    - ubuntu-make

# - name: Install Google Chrome
#   command: wget -O /tmp/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; dpkg -i /tmp/google-chrome-stable_current_amd64.deb

- name: Install Googe Chrome (stable)
  tags: [browser]
  apt: pkg={{item}} state=present
  with_items:
    - google-chrome-stable

- name: Install Spotify
  tags: [music]
  apt: pkg={{item}} allow_unauthenticated=true state=present
  with_items:
    - spotify-client

- name: Install Google Talk Plugin
  apt: pkg={{item}} state=present
  with_items:
    - google-talkplugin

- stat: path=/home/{{main_user}}/programs
  register: programs_folder

- name: Create 'programs' dir for Ubuntu Make installations
  file: path="/home/{{main_user}}/programs"
        state=directory
        mode="u+rwx,o-rwx"
        owner="{{main_user}}"
  when: programs_folder.stat.exists == False

- include_tasks: pypy.yml
  tags: [dev, pypy, python]

- include_tasks: nodejs.yml
  tags: [dev, nodejs]

- include_tasks: rstudio.yml
  tags: [rstudio, rlang]

- include_tasks: deluge.yml
  tags: [torrents, deluge]

- include_tasks: nvidia-video-driver.yml
  tags: [gaming, nvidia]

- include_tasks: steam.yml
  tags: [gaming, steam]

- include_tasks: itchio.yml
  tags: [gaming, itchio]

# GetDeb only hosts the PyCharm Community Edition, not Professional
#- include_tasks: pycharm-getdeb-repo.yml
#  tags: [dev, pycharm]

- include_tasks: pycharm-professional-umake.yml
  tags: [dev, pycharm]

- include_tasks: visual-studio-code-deb.yml
  tags: [dev, vscode]

- include_tasks: smartgit.yml
  tags: [dev, smartgit]

- include_tasks: gitkraken.yml
  tags: [dev, gitkraken]

- include_tasks: terminal_theme.yml
# - include_tasks: erlang-elixir.yml
# - include_tasks: crashplan.yml

- include_tasks: firefox-developer-edition-umake.yml
  tags: [dev, firefox, browser]

# - include_tasks: jetbrains-toolbox.yml
- include_tasks: dropbox.yml
  tags: [dropbox]

- include_tasks: openshot.yml
  tags: [video, openshot]

- include_tasks: etcher.yml
  tags: [etcher]

# No longer required, using Galaxy role angstwad.docker_ubuntu instead
# - include_tasks: docker.yml

# sudo usermod -aG docker $USER
- name: Add primary user to the 'docker' group
  user: name={{main_user}} groups=docker append=yes

# - include_tasks: mono-xamarin.yml
# - incliude: dotnet-core.yml

# Add line:
# PATH=$PATH:${HOME}/.local/bin
# to ~/.bashrc for the main_user
# if not present
