---

- name: Add proper Node.js v8.x to repo list
  shell: curl -sL curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

# - include: delete-apt-cache-hack.yml

- name: Install proper Node.js v8.x
  apt: pkg=nodejs state=present update_cache=yes cache_valid_time=3600

- name: Make nodejs binary 'node' rather than 'nodejs'
  # sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
  alternatives: name=node
                link=/usr/bin/node
                path=/usr/bin/nodejs
                priority=10

- name: Install nvm as {{main_user}}
  shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{nvm_version}}/install.sh | bash"
  become_user: "{{main_user}}"

- name: Add NVM_HOME to /home/{{main_user}}/.profile
  lineinfile:
    path: "/home/{{main_user}}/.profile"
    line: 'export NVM_DIR="$HOME/.nvm"'
  become_user: "{{main_user}}"

- name: Add source ~/.nvm/nvm.sh in /home/{{main_user}}/.profile
  lineinfile:
    path: "/home/{{main_user}}/.profile"
    line: '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"]'
  become_user: "{{main_user}}"

# Global install - probably not what you want really
#
#- name: Install nvm (globally in /usr/local/nvm)
#  shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{nvm_version}}/install.sh | NVM_DIR=/usr/local/nvm bash"
#
#- name: Add NVM_HOME to /home/{{main_user}}/.profile
#  lineinfile:
#    path: "/home/{{main_user}}/.profile"
#    line: 'export NVM_DIR="/usr/local/nvm"'
#- name: Add source ~/.nvm/nvm.sh in /home/{{main_user}}/.profile
#  lineinfile:
#    path: "/home/{{main_user}}/.profile"
#    line: '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"]'