---
- name: Add PyCharm GetDeb repo key
  apt_key: url=http://archive.getdeb.net/getdeb-archive.key state=present

- name: Add PyCharm GetDeb repo
  apt_repository:
    repo='deb http://archive.getdeb.net/ubuntu {{ubuntu_release}}-getdeb apps'
    filename='pycharm'
    state=present

- name: Install PyCharm
  apt: pkg={{item}} update_cache=yes state=present
  with_items:
    - pycharm
