
- name: Add PyPy ppa repo key
  apt_key: id='68854915' keyserver='keyserver.ubuntu.com'

# sudo add-apt-repository ppa:pypy/ppa
- name: Add PyPy PPA
#  apt_repository: repo='ppa:pypy/ppa'
#                  codename='{{ ubuntu_release }}'
  command: apt-add-repository -y ppa:pypy/ppa

# - include: delete-apt-cache-hack.yml

# sudo apt-get install pypy
- name: Install PyPy
  apt: pkg={{item}} update_cache=yes state=present
  with_items:
    - pypy