---
- name: Install Python & associated tools
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python-pip
    - python3-pip
    - python-virtualenv
    - python3-virtualenv
    - python-dev
    - python3-dev
    - virtualenvwrapper
