---
# Add repos
- name: Add multiverse repo
  apt_repository: repo="{{item}}" update_cache=false
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ubuntu_release}} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ubuntu_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ubuntu_release}}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ubuntu_release}}-updates multiverse'

- name: Add Canonical Archive Repo
  apt_repository: repo='deb http://archive.canonical.com/ {{ ubuntu_release }} partner' state=present filename='canonical-archive'

- name: Add Ubuntu Make PPA
  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make' codename='{{ ubuntu_release_lts }}'
  #command: apt-add-repository -y ppa:ubuntu-desktop/ubuntu-make

# - include_tasks: delete-apt-cache-hack.yml

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600
