---
- name: Add RStudio repo signing key
  apt_key: id=E084DAB9
           keyserver=keyserver.ubuntu.com
           state=present

- name: Add RStudio repo
  apt_repository: repo='deb {{ cran_mirror }}/bin/linux/ubuntu xenial/'
                  state=present
                  filename='r-lang'

#- name: Update APT cache
#  apt: update_cache=yes

- include: delete-apt-cache-hack.yml

- name: Install R
  apt: name={{item}} update_cache=yes state=latest
  with_items:
    - r-base
    - r-base-dev

- name: Install RStudio DEB package
  apt: deb="https://download1.rstudio.org/rstudio-{{ rstudio_version }}-amd64.deb"
       # checksum={{rstudio_checksum}}
  become: yes
  ignore_errors: yes