---
- name: Add RStudio repo signing key
  apt_key: id=E084DAB9
           keyserver=keyserver.ubuntu.com
           state=present

- name: Add RStudio repo
  apt_repository: repo='deb http://cran.ms.unimelb.edu.au/bin/linux/ubuntu xenial/'
                  state=present
                  filename='r-lang'
                  update_cache=yes

- name: Install R
  apt: name={{item}} state=latest
  with_items:
    - r-base
    - r-base-dev

- name: Install RStudio DEB package
  apt: deb="https://download1.rstudio.org/rstudio-{{rstudio_version}}-amd64.deb"
       # checksum={{rstudio_checksum}}
  become: yes
  ignore_errors: yes