---
- name: Add RStudio repo signing key
  apt_key: id=E084DAB9
           keyserver=keyserver.ubuntu.com
           state=present

- name: Add RStudio repo
  apt_repository: repo='deb {{ cran_mirror }}/bin/linux/ubuntu {{ubuntu_release}}/'
                  state=present
                  filename='r-lang'

# - include: delete-apt-cache-hack.yml

- name: Install R
  apt: name={{item}} update_cache=yes cache_valid_time=3600 state=latest
  with_items:
    - r-base
    - r-base-dev

- name: Install RStudio DEB package
  apt: deb="https://download1.rstudio.org/rstudio-{{ rstudio_version }}-amd64.deb"
       # checksum={{rstudio_checksum}}
  become: yes
  ignore_errors: yes