---

- name: Install Mercurial (hg)
  apt: name=mercurial state=latest

- name: Install SmartGit DEB package
  shell: "curl http://www.syntevo.com/static/smart/download/smartgithg/archive/smartgit-8_0_4.deb >/tmp/smartgit-8_0_4.deb && dpkg -i /tmp/smartgit-8_0_4.deb"
  become: yes

# - name: Install SmartGit DEB package
#   apt: deb="http://www.syntevo.com/static/smart/download/smartgithg/archive/smartgit-{{smartgit_version}}.deb"
#        allow_unauthenticated=yes
#        # deb="https://www.syntevo.com/static/smart/download/smartgit/smartgit-{{smartgit_version}}.deb"
#        # checksum={{smartgit_checksum}}
#   become: yes
