- name: Accept Steam license
  debconf: name=steam question='steam/question' value='I AGREE' vtype='select'

- name: Accept Steam license (part 2)
  debconf: name=steam question='steam/license' value='' vtype='note'

- name: Install latest Steam
  apt: deb=https://steamcdn-a.akamaihd.net/client/installer/steam.deb

- name: Install steamcmd
  apt: pkg=steamcmd update_cache=yes cache_valid_time=3600 state=present
